name: build
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.21.x'
          cache: false
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
